//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class netcode {
  public static int netcode_init() {
    int ret = netcodePINVOKE.netcode_init();
    return ret;
  }

  public static void netcode_term() {
    netcodePINVOKE.netcode_term();
  }

  public static void netcode_log_level(int level) {
    netcodePINVOKE.netcode_log_level(level);
  }

  public static void netcode_random_bytes(SWIGTYPE_p_uint8_t data, int bytes) {
    netcodePINVOKE.netcode_random_bytes(SWIGTYPE_p_uint8_t.getCPtr(data), bytes);
  }

  public static SWIGTYPE_p_netcode_client_t netcode_client_create(string address, double time) {
    global::System.IntPtr cPtr = netcodePINVOKE.netcode_client_create(address, time);
    SWIGTYPE_p_netcode_client_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_netcode_client_t(cPtr, false);
    return ret;
  }

  public static void netcode_client_destroy(SWIGTYPE_p_netcode_client_t client) {
    netcodePINVOKE.netcode_client_destroy(SWIGTYPE_p_netcode_client_t.getCPtr(client));
  }

  public static void netcode_client_connect(SWIGTYPE_p_netcode_client_t client, SWIGTYPE_p_uint8_t connect_token) {
    netcodePINVOKE.netcode_client_connect(SWIGTYPE_p_netcode_client_t.getCPtr(client), SWIGTYPE_p_uint8_t.getCPtr(connect_token));
  }

  public static void netcode_client_update(SWIGTYPE_p_netcode_client_t client, double time) {
    netcodePINVOKE.netcode_client_update(SWIGTYPE_p_netcode_client_t.getCPtr(client), time);
  }

  public static void netcode_client_send_packet(SWIGTYPE_p_netcode_client_t client, SWIGTYPE_p_uint8_t packet_data, int packet_bytes) {
    netcodePINVOKE.netcode_client_send_packet(SWIGTYPE_p_netcode_client_t.getCPtr(client), SWIGTYPE_p_uint8_t.getCPtr(packet_data), packet_bytes);
  }

  public static SWIGTYPE_p_void netcode_client_receive_packet(SWIGTYPE_p_netcode_client_t client, SWIGTYPE_p_int packet_bytes) {
    global::System.IntPtr cPtr = netcodePINVOKE.netcode_client_receive_packet(SWIGTYPE_p_netcode_client_t.getCPtr(client), SWIGTYPE_p_int.getCPtr(packet_bytes));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static void netcode_client_free_packet(SWIGTYPE_p_netcode_client_t client, SWIGTYPE_p_void packet) {
    netcodePINVOKE.netcode_client_free_packet(SWIGTYPE_p_netcode_client_t.getCPtr(client), SWIGTYPE_p_void.getCPtr(packet));
  }

  public static void netcode_client_disconnect(SWIGTYPE_p_netcode_client_t client) {
    netcodePINVOKE.netcode_client_disconnect(SWIGTYPE_p_netcode_client_t.getCPtr(client));
  }

  public static int netcode_client_state(SWIGTYPE_p_netcode_client_t client) {
    int ret = netcodePINVOKE.netcode_client_state(SWIGTYPE_p_netcode_client_t.getCPtr(client));
    return ret;
  }

  public static int netcode_client_index(SWIGTYPE_p_netcode_client_t client) {
    int ret = netcodePINVOKE.netcode_client_index(SWIGTYPE_p_netcode_client_t.getCPtr(client));
    return ret;
  }

  public static int netcode_generate_connect_token(int num_server_addresses, SWIGTYPE_p_p_char server_addresses, int expire_seconds, SWIGTYPE_p_uint64_t client_id, SWIGTYPE_p_uint64_t protocol_id, SWIGTYPE_p_uint64_t sequence, SWIGTYPE_p_uint8_t private_key, SWIGTYPE_p_uint8_t connect_token) {
    int ret = netcodePINVOKE.netcode_generate_connect_token(num_server_addresses, SWIGTYPE_p_p_char.getCPtr(server_addresses), expire_seconds, SWIGTYPE_p_uint64_t.getCPtr(client_id), SWIGTYPE_p_uint64_t.getCPtr(protocol_id), SWIGTYPE_p_uint64_t.getCPtr(sequence), SWIGTYPE_p_uint8_t.getCPtr(private_key), SWIGTYPE_p_uint8_t.getCPtr(connect_token));
    if (netcodePINVOKE.SWIGPendingException.Pending) throw netcodePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_netcode_server_t netcode_server_create(string bind_address, string public_address, SWIGTYPE_p_uint64_t protocol_id, SWIGTYPE_p_uint8_t private_key, double time) {
    global::System.IntPtr cPtr = netcodePINVOKE.netcode_server_create(bind_address, public_address, SWIGTYPE_p_uint64_t.getCPtr(protocol_id), SWIGTYPE_p_uint8_t.getCPtr(private_key), time);
    SWIGTYPE_p_netcode_server_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_netcode_server_t(cPtr, false);
    if (netcodePINVOKE.SWIGPendingException.Pending) throw netcodePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void netcode_server_start(SWIGTYPE_p_netcode_server_t server, int max_clients) {
    netcodePINVOKE.netcode_server_start(SWIGTYPE_p_netcode_server_t.getCPtr(server), max_clients);
  }

  public static void netcode_server_update(SWIGTYPE_p_netcode_server_t client, double time) {
    netcodePINVOKE.netcode_server_update(SWIGTYPE_p_netcode_server_t.getCPtr(client), time);
  }

  public static int netcode_server_client_connected(SWIGTYPE_p_netcode_server_t server, int client_index) {
    int ret = netcodePINVOKE.netcode_server_client_connected(SWIGTYPE_p_netcode_server_t.getCPtr(server), client_index);
    return ret;
  }

  public static void netcode_server_disconnect_client(SWIGTYPE_p_netcode_server_t server, int client_index) {
    netcodePINVOKE.netcode_server_disconnect_client(SWIGTYPE_p_netcode_server_t.getCPtr(server), client_index);
  }

  public static void netcode_server_disconnect_all_clients(SWIGTYPE_p_netcode_server_t server) {
    netcodePINVOKE.netcode_server_disconnect_all_clients(SWIGTYPE_p_netcode_server_t.getCPtr(server));
  }

  public static void netcode_server_send_packet(SWIGTYPE_p_netcode_server_t server, int client_index, SWIGTYPE_p_uint8_t packet_data, int packet_bytes) {
    netcodePINVOKE.netcode_server_send_packet(SWIGTYPE_p_netcode_server_t.getCPtr(server), client_index, SWIGTYPE_p_uint8_t.getCPtr(packet_data), packet_bytes);
  }

  public static SWIGTYPE_p_void netcode_server_receive_packet(SWIGTYPE_p_netcode_server_t server, int client_index, SWIGTYPE_p_int packet_bytes) {
    global::System.IntPtr cPtr = netcodePINVOKE.netcode_server_receive_packet(SWIGTYPE_p_netcode_server_t.getCPtr(server), client_index, SWIGTYPE_p_int.getCPtr(packet_bytes));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static void netcode_server_free_packet(SWIGTYPE_p_netcode_server_t server, SWIGTYPE_p_void packet) {
    netcodePINVOKE.netcode_server_free_packet(SWIGTYPE_p_netcode_server_t.getCPtr(server), SWIGTYPE_p_void.getCPtr(packet));
  }

  public static int netcode_server_num_clients_connected(SWIGTYPE_p_netcode_server_t server) {
    int ret = netcodePINVOKE.netcode_server_num_clients_connected(SWIGTYPE_p_netcode_server_t.getCPtr(server));
    return ret;
  }

  public static void netcode_server_destroy(SWIGTYPE_p_netcode_server_t server) {
    netcodePINVOKE.netcode_server_destroy(SWIGTYPE_p_netcode_server_t.getCPtr(server));
  }

  public static void netcode_sleep(double seconds) {
    netcodePINVOKE.netcode_sleep(seconds);
  }

  public static double netcode_time() {
    double ret = netcodePINVOKE.netcode_time();
    return ret;
  }

  public static readonly int NETCODE_BIG_ENDIAN = netcodePINVOKE.NETCODE_BIG_ENDIAN_get();
  public static readonly int NETCODE_PLATFORM_WINDOWS = netcodePINVOKE.NETCODE_PLATFORM_WINDOWS_get();
  public static readonly int NETCODE_PLATFORM_MAC = netcodePINVOKE.NETCODE_PLATFORM_MAC_get();
  public static readonly int NETCODE_PLATFORM_UNIX = netcodePINVOKE.NETCODE_PLATFORM_UNIX_get();
  public static readonly int NETCODE_PLATFORM = netcodePINVOKE.NETCODE_PLATFORM_get();
  public static readonly int NETCODE_CONNECT_TOKEN_BYTES = netcodePINVOKE.NETCODE_CONNECT_TOKEN_BYTES_get();
  public static readonly int NETCODE_KEY_BYTES = netcodePINVOKE.NETCODE_KEY_BYTES_get();
  public static readonly int NETCODE_MAC_BYTES = netcodePINVOKE.NETCODE_MAC_BYTES_get();
  public static readonly int NETCODE_NONCE_BYTES = netcodePINVOKE.NETCODE_NONCE_BYTES_get();
  public static readonly int NETCODE_MAX_SERVERS_PER_CONNECT = netcodePINVOKE.NETCODE_MAX_SERVERS_PER_CONNECT_get();
  public static readonly int NETCODE_CLIENT_STATE_CONNECT_TOKEN_EXPIRED = netcodePINVOKE.NETCODE_CLIENT_STATE_CONNECT_TOKEN_EXPIRED_get();
  public static readonly int NETCODE_CLIENT_STATE_INVALID_CONNECT_TOKEN = netcodePINVOKE.NETCODE_CLIENT_STATE_INVALID_CONNECT_TOKEN_get();
  public static readonly int NETCODE_CLIENT_STATE_CONNECTION_TIMED_OUT = netcodePINVOKE.NETCODE_CLIENT_STATE_CONNECTION_TIMED_OUT_get();
  public static readonly int NETCODE_CLIENT_STATE_CONNECTION_RESPONSE_TIMEOUT = netcodePINVOKE.NETCODE_CLIENT_STATE_CONNECTION_RESPONSE_TIMEOUT_get();
  public static readonly int NETCODE_CLIENT_STATE_CONNECTION_REQUEST_TIMEOUT = netcodePINVOKE.NETCODE_CLIENT_STATE_CONNECTION_REQUEST_TIMEOUT_get();
  public static readonly int NETCODE_CLIENT_STATE_CONNECTION_DENIED = netcodePINVOKE.NETCODE_CLIENT_STATE_CONNECTION_DENIED_get();
  public static readonly int NETCODE_CLIENT_STATE_DISCONNECTED = netcodePINVOKE.NETCODE_CLIENT_STATE_DISCONNECTED_get();
  public static readonly int NETCODE_CLIENT_STATE_SENDING_CONNECTION_REQUEST = netcodePINVOKE.NETCODE_CLIENT_STATE_SENDING_CONNECTION_REQUEST_get();
  public static readonly int NETCODE_CLIENT_STATE_SENDING_CONNECTION_RESPONSE = netcodePINVOKE.NETCODE_CLIENT_STATE_SENDING_CONNECTION_RESPONSE_get();
  public static readonly int NETCODE_CLIENT_STATE_CONNECTED = netcodePINVOKE.NETCODE_CLIENT_STATE_CONNECTED_get();
  public static readonly int NETCODE_SOCKET_IPV6 = netcodePINVOKE.NETCODE_SOCKET_IPV6_get();
  public static readonly int NETCODE_SOCKET_IPV4 = netcodePINVOKE.NETCODE_SOCKET_IPV4_get();
  public static readonly int NETCODE_MAX_CLIENTS = netcodePINVOKE.NETCODE_MAX_CLIENTS_get();
  public static readonly int NETCODE_MAX_PACKET_SIZE = netcodePINVOKE.NETCODE_MAX_PACKET_SIZE_get();
  public static readonly int NETCODE_LOG_LEVEL_NONE = netcodePINVOKE.NETCODE_LOG_LEVEL_NONE_get();
  public static readonly int NETCODE_LOG_LEVEL_INFO = netcodePINVOKE.NETCODE_LOG_LEVEL_INFO_get();
  public static readonly int NETCODE_LOG_LEVEL_ERROR = netcodePINVOKE.NETCODE_LOG_LEVEL_ERROR_get();
  public static readonly int NETCODE_LOG_LEVEL_DEBUG = netcodePINVOKE.NETCODE_LOG_LEVEL_DEBUG_get();
}
